name: Remote SSH Pull latest
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Execute remote SSH commands using password
        uses: appleboy/ssh-action@v1
        with:
          host: api.kaigarrod.co.uk
          username: ubuntu
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            cd dockerised-flask-film-app-backend-api
            git pull
            sudo docker compose up --build -d